version: "2"

run:
  timeout: 5s

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1022
        - -QF1008
  exclusions:
    generated: lax    


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
